extends Node

# This script centralizes all the translated text for the title_page_ui.gd scene.

const ADD_BOT_TEXT = {
	'ar': 'إضافة بوت',
	'bn': 'বট যোগ করুন',
	'de': 'Bot\nHinzufügen',
	'en': 'Add Bot',
	'es': 'Añadir Bot',
	'fr': 'Ajouter Bot',
	'he': 'הוסף בוט',
	'hi': 'बॉट जोड़ें',
	'id': 'Tambah Bot',
	'it': 'Aggiungi Bot',
	'ja': 'ボットを追加',
	'ko': '봇 추가',
	'nl': 'Bot Toevoegen',
	'pl': 'Dodaj Bota',
	'pt': 'Adicionar Bot',
	'ru': 'Добавить Бота',
	'th': 'เพิ่มบอท',
	'tr': 'Bot Ekle',
	'zh-Hans': '添加机器人',
	'zh-Hant': '新增機器人',
}

const CONNECTED_WAITING_FOR_HOST_TEXT = {
	'ar': 'متصل! في انتظار المضيف...',
	'bn': 'সংযুক্ত! হোস্টের জন্য অপেক্ষা করা হচ্ছে...',
	'de': 'Verbunden! Warte auf den Host...',
	'en': 'Connected! Waiting for host...',
	'es': '¡Conectado! Esperando al anfitrión...',
	'fr': 'Connecté ! En attente de l\'hôte...',
	'he': 'מחובר! ממתין למארח...',
	'hi': 'जुड़ गया! होस्ट की प्रतीक्षा में...',
	'id': 'Terhubung! Menunggu host...',
	'it': 'Connesso! In attesa dell\'host...',
	'ja': '接続しました！ホストを待っています...',
	'ko': '연결되었습니다! 호스트를 기다리는 중...',
	'nl': 'Verbonden! Wachten op host...',
	'pl': 'Połączono! Oczekiwanie na hosta...',
	'pt': 'Conectado! Aguardando o anfitrião...',
	'ru': 'Подключено! Ожидание хоста...',
	'th': 'เชื่อมต่อแล้ว! กำลังรอโฮสต์...',
	'tr': 'Bağlandı! Sunucu bekleniyor...',
	'zh-Hans': '已连接！等待主机...',
	'zh-Hant': '已連接！等待主機...',
}

const CONNECTING_TEXT = {
	'ar': 'جارٍ الاتصال...',
	'bn': 'সংযোগ করা হচ্ছে...',
	'de': 'Verbinde...',
	'en': 'Connecting...',
	'es': 'Conectando...',
	'fr': 'Connexion...',
	'he': 'מתחבר...',
	'hi': 'कनेक्ट हो रहा है...',
	'id': 'Menghubungkan...',
	'it': 'Connessione...',
	'ja': '接続中...',
	'ko': '연결 중...',
	'nl': 'Verbinden...',
	'pl': 'Łączenie...',
	'pt': 'Conectando...',
	'ru': 'Подключение...',
	'th': 'กำลังเชื่อมต่อ...',
	'tr': 'Bağlanılıyor...',
	'zh-Hans': '连接中...',
	'zh-Hant': '連線中...',
}

const FAILED_TO_CONNECT_TEXT = {
	'ar': 'فشل الاتصال.',
	'bn': 'সংযোগ করতে ব্যর্থ।',
	'de': 'Verbindung fehlgeschlagen.',
	'en': 'Failed to connect.',
	'es': 'Fallo al conectar.',
	'fr': 'Échec de la connexion.',
	'he': 'החיבור נכשל.',
	'hi': 'कनेक्ट करने में विफल।',
	'id': 'Gagal terhubung.',
	'it': 'Connessione non riuscita.',
	'ja': '接続に失敗しました。',
	'ko': '연결에 실패했습니다.',
	'nl': 'Verbinding mislukt.',
	'pl': 'Nie udało się połączyć.',
	'pt': 'Falha na conexão.',
	'ru': 'Не удалось подключиться.',
	'th': 'การเชื่อมต่อล้มเหลว',
	'tr': 'Bağlantı kurulamadı.',
	'zh-Hans': '连接失败。',
	'zh-Hant': '連線失敗。',
}

const HOST_NEW_GAME_TEXT = {
	'ar': 'استضافة\nلعبة جديدة',
	'bn': 'নতুন গেম\nহোস্ট করুন',
	'de': 'Neues Spiel\nStarten',
	'en': 'Host New\nGame',
	'es': 'Crear Nueva\nPartida',
	'fr': 'Héberger\nNouvelle Partie',
	'he': 'צור\nמשחק חדש',
	'hi': 'नया गेम\nहोस्ट करें',
	'id': 'Host Game\nBaru',
	'it': 'Ospita Nuova\nPartita',
	'ja': '新しいゲーム\nをホスト',
	'ko': '새 게임\n호스트',
	'nl': 'Nieuw Spel\nHosten',
	'pl': 'Hostuj Nową\nGrę',
	'pt': 'Hostear Novo\nJogo',
	'ru': 'Создать\nНовую Игру',
	'th': 'โฮสต์เกม\nใหม่',
	'tr': 'Yeni Oyun\nKur',
	'zh-Hans': '主持新\n游戏',
	'zh-Hant': '主持新\n遊戲',
}

const START_GAME_TEXT = {
	'ar': 'ابدأ اللعبة',
	'bn': 'খেলা শুরু করুন',
	'de': 'Spiel\nStarten',
	'en': 'Start Game',
	'es': 'Iniciar Partida',
	'fr': 'Démarrer Partie',
	'he': 'התחל משחק',
	'hi': 'खेल शुरू करें',
	'id': 'Mulai Game',
	'it': 'Inizia Partita',
	'ja': 'ゲームを開始',
	'ko': '게임 시작',
	'nl': 'Start Spel',
	'pl': 'Rozpocznij Grę',
	'pt': 'Iniciar Jogo',
	'ru': 'Начать Игру',
	'th': 'เริ่มเกม',
	'tr': 'Oyunu Başlat',
	'zh-Hans': '开始游戏',
	'zh-Hant': '開始遊戲',
}

const JOIN_GAME_TEXT = {
	'ar': 'الانضمام إلى\nلعبة',
	'bn': 'গেমে\nযোগ দিন',
	'de': 'Spiel\nBeitreten',
	'en': 'Join\nGame',
	'es': 'Unirse a\nPartida',
	'fr': 'Rejoindre\nPartie',
	'he': 'הצטרף\nלמשחק',
	'hi': 'गेम में\nशामिल हों',
	'id': 'Gabung\nGame',
	'it': 'Unisciti a\nPartita',
	'ja': 'ゲーム\nに参加',
	'ko': '게임에\n참가',
	'nl': 'Deelnemen\naan Spel',
	'pl': 'Dołącz do\nGry',
	'pt': 'Juntar-se\nao Jogo',
	'ru': 'Присоединиться\nк Игре',
	'th': 'เข้าร่วม\nเกม',
	'tr': 'Oyuna\nKatıl',
	'zh-Hans': '加入\n游戏',
	'zh-Hant': '加入\n遊戲',
}

const WELCOME_TEXT = {
	'ar': 'أهلاً بك!',
	'bn': 'স্বাগতম!',
	'de': 'Willkommen!',
	'en': 'Welcome!',
	'es': '¡Bienvenido!',
	'fr': 'Bienvenue !',
	'he': 'ברוך הבא!',
	'hi': 'स्वागत है!',
	'id': 'Selamat Datang!',
	'it': 'Benvenuto!',
	'ja': 'ようこそ！',
	'ko': '환영합니다!',
	'nl': 'Welkom!',
	'pl': 'Witaj!',
	'pt': 'Bem-vindo!',
	'ru': 'Добро пожаловать!',
	'th': 'ยินดีต้อนรับ!',
	'tr': 'Hoş Geldiniz!',
	'zh-Hans': '欢迎！',
	'zh-Hant': '歡迎！',
}

const WHAT_IS_YOUR_NAME_TEXT = {
	'ar': 'ما هو اسمك؟',
	'bn': 'আপনার নাম কি?',
	'de': 'Wie heißt du?',
	'en': 'What is your name?',
	'es': '¿Cómo te llamas?',
	'fr': 'Quel est votre nom ?',
	'he': 'מה שמך?',
	'hi': 'आपका नाम क्या है?',
	'id': 'Siapa nama kamu?',
	'it': 'Come ti chiami?',
	'ja': 'お名前は何ですか？',
	'ko': '이름이 무엇입니까?',
	'nl': 'Wat is je naam?',
	'pl': 'Jak masz na imię?',
	'pt': 'Qual é o seu nome?',
	'ru': 'Как вас зовут?',
	'th': 'คุณชื่ออะไร?',
	'tr': 'Adınız nedir?',
	'zh-Hans': '你叫什么名字？',
	'zh-Hant': '你叫什麼名字？',
}
