name: Scheduled Tests

# Run tests on a schedule to catch issues early
on:
  schedule:
    # Run every day at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scheduled-test:
    name: Daily Scheduled Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Godot 4.4.1
      uses: chickensoft-games/setup-godot@v1
      with:
        version: '4.4.1-stable'
        use-dotnet: false

    - name: Cache Godot files
      uses: actions/cache@v3
      with:
        path: |
          .godot/
          .import/
        key: comprehensive-${{ runner.os }}-godot-4.4.1-${{ hashFiles('**/*.import', 'project.godot') }}

    - name: Import project
      run: |
        godot --headless --editor --quit

    - name: Run daily test suite
      run: |
        echo "Running daily scheduled tests..."
        echo "Date: $(date)"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"

        # Run test suite
        godot --headless tests/test_scene.tscn

        echo "Daily tests completed successfully!"

    - name: Health check summary
      if: always()
      run: |
        echo "=== DAILY HEALTH CHECK SUMMARY ==="
        echo "Date: $(date)"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Test Status: ${{ job.status }}"
        echo "Godot Version: 4.4.1-stable"
        echo "======================================"

        if [ "${{ job.status }}" = "success" ]; then
          echo "✅ Daily health check passed - all systems operational"
        else
          echo "❌ Daily health check failed - investigation needed"
        fi
